// Generated by ChatGPT4

import 'package:flutter/material.dart';

class AspectBox extends StatelessWidget {
  final double aspectRatio;
  final Widget child;

  AspectBox({required this.aspectRatio, required this.child});

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final parentAspectRatio = constraints.maxWidth / constraints.maxHeight;

        if (aspectRatio > parentAspectRatio) {
          // The box is wider than the parent, so limit the height
          final height = constraints.maxWidth / aspectRatio;
          return SizedBox(
              height: height, width: constraints.maxWidth, child: child);
        } else {
          // The box is taller than the parent, so limit the width
          final width = constraints.maxHeight * aspectRatio;
          return SizedBox(
              height: constraints.maxHeight, width: width, child: child);
        }
      },
    );
  }
}
