// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Y9t9DHMtdfEjesbLsaVPMoh5ISraRoA',
    appId: '1:949377327394:web:3bb71c2e23d9ca0246c57b',
    messagingSenderId: '949377327394',
    projectId: 'excercise-companion-uhm-app',
    authDomain: 'excercise-companion-uhm-app.firebaseapp.com',
    storageBucket: 'excercise-companion-uhm-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqF5--LigysBIlZFNLF53ynWA-i33hNHc',
    appId: '1:949377327394:android:76190a06a609feb646c57b',
    messagingSenderId: '949377327394',
    projectId: 'excercise-companion-uhm-app',
    storageBucket: 'excercise-companion-uhm-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN6A_8_b_80SA52HL6Dr14OtyAXGyY9Xo',
    appId: '1:949377327394:ios:f5de9e2ebca1441846c57b',
    messagingSenderId: '949377327394',
    projectId: 'excercise-companion-uhm-app',
    storageBucket: 'excercise-companion-uhm-app.appspot.com',
    iosBundleId: 'com.example.exerciseCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN6A_8_b_80SA52HL6Dr14OtyAXGyY9Xo',
    appId: '1:949377327394:ios:696430970292eaea46c57b',
    messagingSenderId: '949377327394',
    projectId: 'excercise-companion-uhm-app',
    storageBucket: 'excercise-companion-uhm-app.appspot.com',
    iosBundleId: 'com.example.exerciseCompanion.RunnerTests',
  );
}
