// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbFKo1ndw9XUab80s59sPhWPyTT7fc4Iw',
    appId: '1:291032520443:web:21c2a66b9df827e69cc25e',
    messagingSenderId: '291032520443',
    projectId: 'exercise-companion-uhm',
    authDomain: 'exercise-companion-uhm.firebaseapp.com',
    storageBucket: 'exercise-companion-uhm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA45lWsRidImh5_QaEQw2TC98IulTPw38',
    appId: '1:291032520443:android:061e923c001e111b9cc25e',
    messagingSenderId: '291032520443',
    projectId: 'exercise-companion-uhm',
    storageBucket: 'exercise-companion-uhm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0baiAIGtg32Z3Zh2TsQTgtV6vRXc5uHU',
    appId: '1:291032520443:ios:bf9a45eeca8d22f79cc25e',
    messagingSenderId: '291032520443',
    projectId: 'exercise-companion-uhm',
    storageBucket: 'exercise-companion-uhm.appspot.com',
    iosBundleId: 'com.example.exerciseCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0baiAIGtg32Z3Zh2TsQTgtV6vRXc5uHU',
    appId: '1:291032520443:ios:447c34e3b6c835bd9cc25e',
    messagingSenderId: '291032520443',
    projectId: 'exercise-companion-uhm',
    storageBucket: 'exercise-companion-uhm.appspot.com',
    iosBundleId: 'com.example.exerciseCompanion.RunnerTests',
  );
}
